### PR TITLE
Patched to work with cordova@10.0.0

### PR DESCRIPTION
**Pull request by iMrDJAi**
Tested with cordova@10.0.0 and cordova-android@9.0.0, It works fine!
Fix suggested by @staltz (https://github.com/JaneaSystems/nodejs-mobile/issues/239#issue-548915419)  
**Edit:** I also updated cordova-ios to version 6.2.0 to fix a compatibility issue with cordova@10.0.0, then I added some github actions tests to the project.

### CODE REVIEW

**Comment by romuloalves** [comment]
There are some `inputs.file` and `outputs.file` that should be `inputs.dir` and `outputs.dir` in `src/android/build.gradle`. I found that the `nodejs-mobile-react-native` contains the right configs.
Even changing that I couldn't make it work but I think it's something related to my project and native modules.
Let me know if someone couldn't try this changes.

cc: @iMrDJAi

**Comment by iMrDJAi** [comment]
@romuloalves Not sure about that, the only what I found necessary to include there are the `libnode.so` files:
```gradle
    packagingOptions {
        pickFirst 'lib/x86/libnode.so'
        pickFirst 'lib/armeabi-v7a/libnode.so'
        pickFirst 'lib/arm64-v8a/libnode.so'
        pickFirst 'lib/x86_64/libnode.so'
    }
```
If you get an error while building your project post it and I'll see.

**Comment by romuloalves** [comment]
@iMrDJAi 
The error was `Cannot write to file '' specified for property '$1' as it is a directory.`.
It was in the step `BuildNpmModules${abi_name}`.

I found out this line (taking from your PR):
```
227 outputs.file "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/nodejs-project/"
```

I changed this one and lines 220 and 273 too.
They're in this way here: https://github.com/JaneaSystems/nodejs-mobile-react-native/blob/unstable/android/build.gradle#L373

**Comment by iMrDJAi** [comment]
> @iMrDJAi
> The error was `Cannot write to file '' specified for property '$1' as it is a directory.`.
> It was in the step `BuildNpmModules${abi_name}`.
> 
> I found out this line (taking from your PR):
> 
> ```
> 227 outputs.file "${rootProject.buildDir}/nodejs-native-assets-temp-build/nodejs-native-assets-${abi_name}/nodejs-project/"
> ```
> 
> I changed this one and lines 220 and 273 too.
> They're in this way here: https://github.com/JaneaSystems/nodejs-mobile-react-native/blob/unstable/android/build.gradle#L373

@romuloalves  Before doing anything further, try doing a fresh build. Recreate your project again, make sure to update everything, check you Cordova version..
You said it may be your project, there are breaking changes made to Cordova, you can't simply upgrade or change your version with no issues.
If that's not the deal, can you please provide me info about how did you setup your project?

**Review by jaimecbernardo — APPROVED** [review]
LGTM!
Thanks a lot for the contribution and sorry for taking so long to get back to you.

**Pull request merged**
